# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            grim
tagline:          'General Relativistic Implicit Magnetohydrodynamics'
description:      ''
url:              http://afd-illinois.github.io/grim
baseurl:          /grim

author:
  name:           'Mani Chandra'
  url:            http://mchandra.github.io/

# Custom vars
repo:             http://github.com/afd-illinois/grim
